---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure NFS utilities are installed.
  package:
    name: "{{ nfs_packages }}"
    state: present
  notify:
    - 'Restart nfs services'

# Setup/install os speciffic tasks.
- include_tasks: setup-{{ ansible_os_family }}.yml
  notify:
    - Restart nfs server
    - Restart nfs utils

- name: Create /etc/exports.d/ directory
  file:
    path: '/etc/exports.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Ensure exported directories exist
  file:
    path: '{{ item.path }}'
    state: 'directory'
    owner: '{{ item.owner | d("root") }}'
    group: '{{ item.group | d("root") }}'
    mode:  '{{ item.mode  | d("0755") }}'
  with_flattened:
    - '{{ nfs_server__combined_exports }}'
  when: item.path|d() and item.state|d('present') != 'absent' and item.acl|d()

- name: Bind mount requested directories
  mount:
    name: '{{ item.path }}'
    src: '{{ item.bind }}'
    opts: 'bind'
    fstype: 'none'
    state: 'mounted'
  with_flattened:
    - '{{ nfs_server__combined_exports }}'
  when: item.path|d() and item.state|d('present') != 'absent' and item.acl|d() and item.bind|d()

- name: Configure NFS exports
  template:
    src: 'etc/exports.d/ansible.exports.j2'
    dest: '/etc/exports.d/ansible.exports'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'reload nfs'
