---
- name: Ensure rpcbind is running as configured.
  service:
    name: rpcbind
    state: started
    enabled: true
  notify:
    - "Restart nfs-kernel-server service"
    - "Restart nfs-common service"
