---

- name: Configure NFS Server
  hosts: [ 'devo_service_nfs_server' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: devo.etc_services
      tags: [ 'role::etc_services', 'role::ferm' ]
      etc_services__dependent_list:
        - '{{ nfs_server__etc_services__dependent_list }}'

    - role: devo.ferm
      tags: [ 'role::ferm' ]
      ferm__dependent_rules:
        - '{{ nfs_server__ferm__dependent_rules }}'

    - role: devo.tcpwrappers
      tags: [ 'role::tcpwrappers' ]
      tcpwrappers__dependent_allow:
        - '{{ nfs_server__tcpwrappers__dependent_allow }}'

    - role: devo.nfs_server
      tags: [ 'role::nfs_server' ]
